### ISSUE TITLE
Create new workflow for bpf_performance

### ISSUE THREAD

**Issue by rectified95** [microsoft/ebpf-for-windows#2878]
### Describe the feature you'd like supported

Currently, the performance job is declared in the same workflow as our CICD.

It can also be triggered by hand, but it's configured such that nothing else runs on manual dispatch apart from the build and this job.
We should be able to trigger the CICD by hand and have that match the nightly runs. 

### Proposed solution

Split into separate workflow

**Comment by Alan-Jowett** [comment]
Alternative proposal:
Pass it as a parameter to the scheduled workload.

```yml
  # Permit manual runs of the workflow.
  workflow_dispatch:
    # Provide arguments to the workflow_dispatch event.
    inputs:
      type:
        description: 'Type of test to run'
        required: true
        type: choice
        options:
        - 'unit_tests'
        - 'netebpf_ext_unit_tests'
        - 'bpf2c'
        - 'bpf2c_conformance'
        - 'driver_ws2019'
        - 'driver_ws2022'
        - 'driver_native_only_ws2019'
        - 'driver_native_only_ws2022'
        - 'ossar'
        - 'bpf2c_fuzzer'
        - 'bpf2c_fuzzer_scheduled'
        - 'execution_context_fuzzer'
        - 'verifier_fuzzer'
        - 'verifier_fuzzer_scheduled'
        - 'core_helper_fuzzer'
        - 'netebpfext_fuzzer'
        - 'cilium_tests'
        - 'stress'
        - 'sanitize_unit_tests'
        - 'fault_injection'
        - 'fault_injection_netebpfext_unit'
        - 'quick_user_mode_multi_threaded_stress_test'
        - 'user_mode_multi_threaded_stress_test'
        - 'km_mt_stress_tests'
        - 'km_mt_stress_tests_restart_extension'
        - 'performance'
        - 'performance_with_profile'
```
